dist: trusty
language: php
php:
  - 5.5
  - 5.6
  - 7.0

script:
  - wget https://github.com/magento/magento2/archive/2.0.2.zip
  - unzip -qq 2.0.2.zip
  - cd magento2-2.0.2/
  - wget https://gist.githubusercontent.com/centerax/5e42abec89d62a1308ba/raw/4b3242361c0690e234266afb3520c2940ac1055a/auth.json
  - composer install
  - composer require ebizmarts/magento2-magemonkey:dev-develop
  - /bin/cp ../phpunit_config.xml dev/tests/unit/
  - ./vendor/bin/phpunit -c dev/tests/unit/phpunit_config.xml
  - ./vendor/bin/phpunit -c dev/tests/unit/phpunit_config.xml --coverage-text
